const cosmonautData = [
    ['Sentinel', 'moon surface', 'white', 'plain', 'red', 'none', 0],
    ['Secret Network', 'space', 'white', 'plain', 'red', 'none', 0],
    ['Chihuahua', 'space', 'colored', 'plain', 'purple', 'gloves', 1],
    ['Chihuahua', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Chihuahua', 'spaceship', 'white', 'plain', 'pink', 'stripes', 1],
    ['Cosmos Hub', 'moon surface', 'white', 'plain', 'blue', 'none', 0],
    ['Chihuahua', 'space', 'white', 'plain', 'blue', 'stripes', 1],
    ['Racoon', 'space', 'colored', 'plain', 'pink', 'stripes', 1],
    ['Chihuahua', 'space', 'white', 'plain', 'cyan', 'stripes', 1],
    ['Chihuahua', 'space', 'white', 'plain', 'green', 'stripes', 1],
    ['Secret Network', 'spaceship', 'white', 'plain', 'green', 'none', 0],
    ['Terra Luna', 'planet surface', 'colored', 'plain', 'purple', 'none', 0],
    ['BitSong', 'space', 'white', 'plain', 'orange', 'stripes, music notes', 2],
    ['Secret Network', 'space with moon', 'white', 'plain', 'green', 'gloves', 1],
    ['Regen Network', 'space', 'white', 'plain', 'pink', 'stripes', 1],
    ['Terra Luna', 'space', 'white', 'plain', 'orange', 'none', 0],
    ['Osmosis', 'planet surface', 'white', 'plain', 'orange', 'stripes', 1],
    ['Akash Network', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Osmosis', 'moon surface', 'white', 'plain', 'orange', 'none', 0],
    ['Akash Network', 'space', 'colored', 'diagonal gradient', 'green', 'none', 0],
    ['BitSong', 'space', 'white', 'plain', 'purple', 'none', 0],
    ['Sentinel', 'space', 'white', 'plain', 'cyan', 'gloves', 1],
    ['Cosmos Hub', 'space', 'white', 'plain', 'pink', 'none', 0],
    ['Chihuahua', 'space', 'white', 'plain', 'orange', 'gloves', 1],
    ['Chihuahua', 'space', 'white', 'plain', 'red', 'none', 0],
    ['Sentinel', 'planet surface', 'colored', 'plain', 'pink', 'none', 0],
    ['Cosmos Hub', 'space', 'white', 'plain', 'orange', 'gloves', 1],
    ['Osmosis', 'space', 'colored', 'plain', 'blue', 'none', 0],
    ['Stargaze', 'space', 'colored', 'plain', 'orange', 'airdrop basket', 1],
    ['Sentinel', 'planet surface', 'colored', 'plain', 'pink', 'none', 0],
    ['Juno', 'space', 'colored', 'plain', 'red', 'gloves, boots', 2],
    ['crypto.com', 'space', 'white', 'diagonal gradient', 'green', 'none', 0],
    ['Akash Network', 'space', 'white', 'plain', 'green', 'gloves, stripes', 2],
    ['crypto.com', 'spaceship', 'white', 'horizontal gradient', 'purple', 'stripes', 1],
    ['Sentinel', 'space', 'white', 'diagonal gradient', 'green', 'none', 0],
    ['Sentinel', 'space', 'gray', 'plain', 'cyan', 'none', 0],
    ['crypto.com', 'alien world', 'white', 'plain', 'green', 'none', 0],
    ['Stargaze', 'space', 'colored', 'horizontal gradient', 'blue', 'stripes, airdrop basket', 2],
    ['Stargaze', 'space', 'gray', 'plain', 'purple', 'airdrop basket', 1],
    ['Racoon', 'space', 'white', 'plain', 'blue', 'gloves', 1],
    ['Terra Luna', 'planet surface', 'white', 'plain', 'green', 'none', 0],
    ['Osmosis', 'planet surface', 'white', 'plain', 'green', 'none', 0],
    ['Chihuahua', 'moon surface', 'white', 'plain', 'purple', 'gloves', 1],
    ['Juno', 'space', 'white', 'horizontal gradient', 'green', 'none', 0],
    ['Terra Luna', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Cosmostation', 'space', 'colored', 'plain', 'purple', 'none', 0],
    ['Akash Network', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Sentinel', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Stargaze', 'space', 'white', 'plain', 'red', 'boots, airdrop basket', 2],
    ['Secret Network', 'spaceship', 'gradient', 'diagonal gradient', 'yellow', 'none', 0],
    ['Sentinel', 'space with planet', 'white', 'horizontal gradient', 'blue', 'none', 0],
    ['Secret Network', 'space', 'gradient', 'plain', 'red', 'gloves', 1],
    ['Chihuahua', 'spaceship', 'white', 'plain', 'green', 'none', 0],
    ['Sentinel', 'planet surface', 'colored', 'plain', 'green', 'none', 0],
    ['Chihuahua', 'planet surface', 'white', 'plain', 'orange', 'none', 0],
    ['Comdex', 'space', 'white', 'plain', 'purple', 'gloves', 1],
    ['Cosmos Hub', 'space with blood moon', 'colored', 'plain', 'cyan', 'stripes', 1],
    ['Comdex', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Stargaze', 'space', 'gradient', 'plain', 'blue', 'stripes', 1],
    ['Terra Luna', 'spaceship', 'gray', 'plain', 'orange', 'none', 0],
    ['Sentinel', 'galaxy', 'colored', 'plain', 'blue', 'none', 0],
    ['Chihuahua', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Osmosis', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Akash Network', 'space', 'white', 'plain', 'green', 'stripes', 1],
    ['crypto.com', 'galaxy', 'white', 'plain', 'blue', 'none', 0],
    ['Osmosis', 'planet surface', 'white', 'plain', 'green', 'boots', 1],
    ['Sentinel', 'spaceship', 'white', 'plain', 'orange', 'boots', 1],
    ['Stargaze', 'space', 'white', 'plain', 'cyan', 'stripes', 1],
    ['Cosmos Hub', 'space', 'white', 'plain', 'red', 'boots', 1],
    ['Akash Network', 'space', 'colored', 'diagonal gradient', 'green', 'gloves', 1],
    ['Terra Luna', 'moon surface', 'colored', 'plain', 'red', 'none', 0],
    ['crypto.com', 'space', 'white', 'plain', 'cyan', 'gloves', 1],
    ['Osmosis', 'planet surface', 'gray', 'plain', 'red', 'none', 0],
    ['Stargaze', 'space', 'white', 'plain', 'purple', 'none', 0],
    ['Terra Luna', 'space', 'white', 'plain', 'green', 'boots, stripes', 2],
    ['Comdex', 'space', 'colored', 'plain', 'green', 'none', 0],
    ['Terra Luna', 'space', 'white', 'diagonal gradient', 'red', 'stripes', 1],
    ['Cosmos Hub', 'space with planet', 'colored', 'plain', 'orange', 'gloves', 1],
    ['Osmosis', 'space', 'gray', 'horizontal gradient', 'green', 'airdrop basket', 1],
    ['Cosmos Hub', 'space', 'colored', 'plain', 'yellow', 'boots', 1],
    ['BitCanna', 'space', 'white', 'plain', 'purple', 'smoke', 1],
    ['crypto.com', 'space', 'colored', 'plain', 'green', 'boots', 1],
    ['Osmosis', 'space', 'colored', 'plain', 'orange', 'none', 0],
    ['Secret Network', 'planet surface', 'white', 'plain', 'yellow', 'none', 0],
    ['Stargaze', 'planet surface', 'white', 'plain', 'green', 'gloves', 1],
    ['Cosmos Hub', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['BitSong', 'space', 'white', 'plain', 'purple', 'stripes, music notes', 2],
    ['Chihuahua', 'space', 'gray', 'plain', 'cyan', 'none', 0],
    ['Juno', 'space', 'white', 'plain', 'blue', 'stripes', 1],
    ['Osmosis', 'space', 'white', 'plain', 'purple', 'stripes', 1],
    ['crypto.com', 'space', 'gradient', 'plain', 'green', 'gloves', 1],
    ['Persistence', 'space', 'gray', 'plain', 'blue', 'stripes', 1],
    ['Secret Network', 'deep field', 'white', 'diagonal gradient', 'green', 'gloves, boots, stripes', 3],
    ['Osmosis', 'planet surface', 'white', 'plain', 'pink', 'airdrop basket', 1],
    ['Cosmos Hub', 'space', 'white', 'plain', 'yellow', 'none', 0],
    ['Chihuahua', 'space', 'white', 'plain', 'green', 'none', 0],
    ['Chihuahua', 'space', 'gray', 'plain', 'green', 'none', 0],
    ['Osmosis', 'planet surface', 'white', 'plain', 'blue', 'gloves', 1],
    ['Osmosis', 'space', 'colored', 'plain', 'yellow', 'none', 0],
    ['Chihuahua', 'space', 'white', 'plain', 'blue', 'stripes', 1],
    ['Chihuahua', 'space', 'colored', 'plain', 'purple', 'none', 0],
    ['Juno', 'space with moon', 'colored', 'plain', 'cyan', 'none', 0],
    ['Osmosis', 'spaceship', 'white', 'plain', 'cyan', 'stripes, airdrop basket', 2],
    ['Terra Luna', 'space', 'colored', 'plain', 'cyan', 'stripes', 1],
    ['Secret Network', 'spaceship', 'white', 'diagonal gradient', 'cyan', 'stripes', 1],
    ['Terra Luna', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Secret Network', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Sentinel', 'space', 'white', 'plain', 'green', 'none', 0],
    ['Persistence', 'alien world', 'white', 'plain', 'green', 'none', 0],
    ['Akash Network', 'planet surface', 'white', 'plain', 'yellow', 'none', 0],
    ['Sentinel', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['crypto.com', 'space', 'white', 'plain', 'red', 'stripes', 1],
    ['Cosmos Hub', 'space', 'white', 'plain', 'red', 'none', 0],
    ['Chihuahua', 'space with planet', 'white', 'plain', 'cyan', 'none', 0],
    ['Terra Luna', 'space', 'gradient', 'plain', 'blue', 'none', 0],
    ['Chihuahua', 'space', 'gradient', 'plain', 'pink', 'none', 0],
    ['Chihuahua', 'space', 'colored', 'plain', 'green', 'none', 0],
    ['Chihuahua', 'space with planet', 'colored', 'plain', 'blue', 'none', 0],
    ['Sentinel', 'space', 'white', 'plain', 'purple', 'none', 0],
    ['BitSong', 'galaxy', 'white', 'plain', 'green', 'gloves, music notes', 2],
    ['Sentinel', 'space', 'white', 'diagonal gradient', 'blue', 'none', 0],
    ['Osmosis', 'space', 'white', 'plain', 'orange', 'stripes', 1],
    ['Comdex', 'space with planet', 'white', 'plain', 'green', 'none', 0],
    ['Juno', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Stargaze', 'space', 'white', 'plain', 'green', 'boots, stripes', 2],
    ['Juno', 'space', 'white', 'plain', 'blue', 'gloves, stripes, comet', 3],
    ['Sentinel', 'space', 'colored', 'plain', 'green', 'boots', 1],
    ['Keplr', 'planet surface', 'white', 'plain', 'purple', 'none', 0],
    ['Terra Luna', 'space', 'white', 'horizontal gradient', 'orange', 'gloves, stripes', 2],
    ['Persistence', 'space with planet', 'white', 'plain', 'purple', 'none', 0],
    ['Terra Luna', 'space with blood moon', 'white', 'plain', 'green', 'gloves', 1],
    ['Chihuahua', 'space center', 'white', 'plain', 'purple', 'gloves, stripes', 2],
    ['Chihuahua', 'space', 'gray', 'plain', 'green', 'none', 0],
    ['BitCanna', 'space', 'white', 'plain', 'blue', 'stripes', 1],
    ['Chihuahua', 'space with moon', 'white', 'plain', 'orange', 'stripes', 1],
    ['Osmosis', 'space', 'white', 'plain', 'cyan', 'stripes, airdrop basket', 2],
    ['Chihuahua', 'space', 'white', 'plain', 'blue', 'stripes', 1],
    ['Cosmos Hub', 'space', 'colored', 'plain', 'orange', 'none', 0],
    ['crypto.com', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Sentinel', 'space', 'white', 'plain', 'orange', 'boots', 1],
    ['Regen Network', 'planet surface', 'white', 'plain', 'blue', 'boots', 1],
    ['Cosmos Hub', 'space', 'white', 'plain', 'pink', 'stripes', 1],
    ['Chihuahua', 'spaceship', 'white', 'plain', 'purple', 'gloves', 1],
    ['Juno', 'space', 'white', 'plain', 'yellow', 'none', 0],
    ['Sentinel', 'space', 'colored', 'plain', 'yellow', 'none', 0],
    ['Terra Luna', 'spaceship', 'white', 'plain', 'pink', 'boots, stripes', 2],
    ['Cosmos Hub', 'space', 'colored', 'plain', 'cyan', 'none', 0],
    ['Regen Network', 'space', 'white', 'plain', 'orange', 'none', 0],
    ['Stargaze', 'space', 'colored', 'plain', 'purple', 'stripes, airdrop basket', 2],
    ['Juno', 'space', 'colored', 'horizontal gradient', 'orange', 'gloves', 1],
    ['Terra Luna', 'spaceship', 'colored', 'plain', 'blue', 'stripes', 1],
    ['Cosmos Hub', 'space', 'white', 'plain', 'orange', 'boots, stripes', 2],
    ['Sentinel', 'galaxy', 'white', 'plain', 'purple', 'none', 0],
    ['Chihuahua', 'space with planet', 'white', 'plain', 'orange', 'none', 0],
    ['Stargaze', 'space with planet', 'white', 'plain', 'pink', 'stripes', 1],
    ['Chihuahua', 'space', 'colored', 'plain', 'green', 'gloves, stripes', 2],
    ['Chihuahua', 'alien world', 'colored', 'plain', 'blue', 'stripes', 1],
    ['Sentinel', 'space', 'white', 'plain', 'yellow', 'stripes', 1],
    ['Secret Network', 'space', 'white', 'plain', 'yellow', 'boots, comet', 2],
    ['crypto.com', 'space', 'white', 'plain', 'green', 'none', 0],
    ['Sentinel', 'space', 'white', 'plain', 'blue', 'stripes', 1],
    ['crypto.com', 'alien world', 'white', 'plain', 'cyan', 'none', 0],
    ['Comdex', 'space', 'colored', 'plain', 'cyan', 'stripes', 1],
    ['Chihuahua', 'space with planet', 'white', 'plain', 'blue', 'none', 0],
    ['Chihuahua', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Chihuahua', 'space', 'white', 'plain', 'cyan', 'none', 0],
    ['crypto.com', 'space', 'colored', 'plain', 'cyan', 'none', 0],
    ['Secret Network', 'space', 'colored', 'plain', 'green', 'none', 0],
    ['Terra Luna', 'space', 'white', 'plain', 'green', 'none', 0],
    ['Terra Luna', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Cosmos Hub', 'space', 'colored', 'plain', 'blue', 'none', 0],
    ['Sentinel', 'galaxy', 'white', 'plain', 'red', 'none', 0],
    ['Juno', 'space', 'white', 'plain', 'green', 'none', 0],
    ['Stargaze', 'space', 'white', 'plain', 'green', 'boots, stripes, airdrop basket', 3],
    ['Chihuahua', 'space', 'colored', 'plain', 'purple', 'none', 0],
    ['Stargaze', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['crypto.com', 'moon surface', 'white', 'plain', 'blue', 'none', 0],
    ['SmartStake', 'planet surface', 'white', 'plain', 'blue', 'none', 0],
    ['Osmosis', 'space', 'gray', 'plain', 'yellow', 'gloves, boots', 2],
    ['crypto.com', 'space with moon', 'white', 'horizontal gradient', 'green', 'none', 0],
    ['Stargaze', 'space with planet', 'white', 'plain', 'yellow', 'airdrop basket', 1],
    ['Terra Luna', 'space', 'colored', 'plain', 'pink', 'none', 0],
    ['Stargaze', 'space', 'white', 'plain', 'purple', 'airdrop basket', 1],
    ['Sentinel', 'space', 'white', 'plain', 'purple', 'none', 0],
    ['Cosmos Hub', 'space', 'colored', 'plain', 'pink', 'none', 0],
    ['Stargaze', 'space', 'white', 'plain', 'blue', 'airdrop basket', 1],
    ['Chihuahua', 'space', 'white', 'plain', 'purple', 'stripes', 1],
    ['Cosmos Hub', 'space center', 'colored', 'plain', 'green', 'none', 0],
    ['crypto.com', 'space', 'white', 'plain', 'pink', 'stripes', 1],
    ['Secret Network', 'space', 'white', 'plain', 'purple', 'none', 0],
    ['Cosmos Hub', 'space', 'white', 'plain', 'orange', 'none', 0],
    ['Chihuahua', 'space', 'white', 'plain', 'orange', 'boots', 1],
    ['Osmosis', 'space', 'colored', 'plain', 'cyan', 'stripes', 1],
    ['Osmosis', 'space', 'white', 'plain', 'orange', 'none', 0],
    ['Cosmos Hub', 'space', 'white', 'plain', 'green', 'boots', 1],
    ['Chihuahua', 'space', 'white', 'plain', 'green', 'none', 0],
    ['Persistence', 'space', 'white', 'plain', 'green', 'stripes', 1],
    ['BitCanna', 'planet surface', 'white', 'plain', 'orange', 'gloves, smoke', 2],
    ['Osmosis', 'space', 'white', 'plain', 'green', 'none', 0],
    ['Stargaze', 'space', 'white', 'plain', 'green', 'none', 0],
    ['BitSong', 'spaceship', 'white', 'horizontal gradient', 'purple', 'none', 0],
    ['Stargaze', 'space', 'gradient', 'plain', 'blue', 'none', 0],
    ['Regen Network', 'spaceship', 'white', 'plain', 'yellow', 'none', 0],
    ['Osmosis', 'space', 'colored', 'diagonal gradient', 'cyan', 'none', 0],
    ['Chihuahua', 'space', 'gradient', 'plain', 'pink', 'gloves, stripes', 2],
    ['Juno', 'planet surface', 'white', 'plain', 'pink', 'none', 0],
    ['Sentinel', 'space', 'white', 'plain', 'green', 'none', 0],
    ['Sentinel', 'space', 'colored', 'diagonal gradient', 'blue', 'comet', 1],
    ['Cosmos Hub', 'space', 'white', 'plain', 'cyan', 'boots, stripes', 2],
    ['Regen Network', 'space with planet', 'white', 'plain', 'green', 'none', 0],
    ['Cosmos Hub', 'space', 'gradient', 'diagonal gradient', 'cyan', 'none', 0],
    ['Juno', 'spaceship', 'white', 'plain', 'green', 'none', 0],
    ['Stargaze', 'planet surface', 'white', 'plain', 'purple', 'stripes', 1],
    ['Persistence', 'space', 'colored', 'plain', 'green', 'stripes, rocket', 2],
    ['Osmosis', 'spaceship', 'white', 'plain', 'orange', 'gloves', 1],
    ['Comdex', 'space with blood moon', 'white', 'plain', 'red', 'gloves', 1],
    ['Osmosis', 'space', 'white', 'plain', 'red', 'comet', 1],
    ['Sentinel', 'planet surface', 'white', 'plain', 'orange', 'none', 0],
    ['Regen Network', 'space', 'white', 'plain', 'cyan', 'none', 0],
    ['Juno', 'space', 'white', 'horizontal gradient', 'cyan', 'none', 0],
    ['Sentinel', 'space', 'gray', 'plain', 'purple', 'none', 0],
    ['Akash Network', 'space with planet', 'white', 'plain', 'yellow', 'none', 0],
    ['Terra Luna', 'space', 'colored', 'plain', 'yellow', 'comet', 1],
    ['Terra Luna', 'space', 'white', 'diagonal gradient', 'green', 'none', 0],
    ['crypto.com', 'space', 'white', 'plain', 'red', 'none', 0],
    ['Akash Network', 'alien world', 'white', 'plain', 'yellow', 'none', 0],
    ['Juno', 'spaceship', 'white', 'plain', 'green', 'none', 0],
    ['BitCanna', 'space', 'white', 'plain', 'green', 'boots', 1],
    ['Stargaze', 'planet surface', 'colored', 'plain', 'green', 'gloves, airdrop basket', 2],
    ['Chihuahua', 'space', 'white', 'plain', 'green', 'gloves, stripes', 2],
    ['Comdex', 'space', 'white', 'plain', 'green', 'none', 0],
    ['Juno', 'space', 'white', 'plain', 'pink', 'none', 0],
    ['Regen Network', 'planet surface', 'white', 'plain', 'yellow', 'gloves', 1],
    ['crypto.com', 'space', 'white', 'plain', 'purple', 'none', 0],
    ['Sentinel', 'space', 'white', 'plain', 'orange', 'none', 0],
    ['Juno', 'space', 'white', 'plain', 'red', 'stripes', 1],
    ['crypto.com', 'space', 'gradient', 'plain', 'red', 'none', 0],
    ['Stargaze', 'planet surface', 'white', 'plain', 'blue', 'none', 0],
    ['Chihuahua', 'space', 'white', 'plain', 'yellow', 'none', 0],
    ['Sentinel', 'space', 'white', 'plain', 'orange', 'boots', 1],
    ['Chihuahua', 'space', 'gray', 'plain', 'red', 'none', 0],
    ['Cosmos Hub', 'space', 'colored', 'plain', 'purple', 'none', 0],
    ['Stargaze', 'space', 'white', 'plain', 'purple', 'boots', 1],
    ['Akash Network', 'space', 'gray', 'plain', 'purple', 'none', 0],
    ['Secret Network', 'space', 'white', 'plain', 'yellow', 'none', 0],
    ['Osmosis', 'space with planet', 'white', 'plain', 'orange', 'none', 0],
    ['Osmosis', 'space', 'white', 'plain', 'blue', 'airdrop basket', 1],
    ['Chihuahua', 'planet surface', 'white', 'plain', 'purple', 'stripes', 1],
    ['Juno', 'moon surface', 'white', 'horizontal gradient', 'green', 'none', 0],
    ['Terra Luna', 'space', 'colored', 'plain', 'blue', 'gloves, boots', 2],
    ['Sentinel', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Regen Network', 'space', 'white', 'plain', 'blue', 'stripes, rocket', 2],
    ['Chihuahua', 'space', 'white', 'plain', 'green', 'none', 0],
    ['Secret Network', 'planet surface', 'white', 'horizontal gradient', 'green', 'gloves', 1],
    ['Stargaze', 'space', 'white', 'plain', 'pink', 'stripes', 1],
    ['Ion', 'spaceship', 'gradient', 'plain', 'green', 'gloves', 1],
    ['Akash Network', 'space', 'white', 'plain', 'green', 'none', 0],
    ['crypto.com', 'space', 'colored', 'plain', 'green', 'none', 0],
    ['Sentinel', 'planet surface', 'white', 'plain', 'blue', 'stripes', 1],
    ['Chihuahua', 'space', 'white', 'plain', 'orange', 'none', 0],
    ['crypto.com', 'space', 'white', 'plain', 'blue', 'gloves', 1],
    ['crypto.com', 'planet surface', 'white', 'plain', 'green', 'gloves', 1],
    ['crypto.com', 'space', 'white', 'plain', 'blue', 'stripes', 1],
    ['Persistence', 'space', 'white', 'plain', 'orange', 'stripes', 1],
    ['crypto.com', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Chihuahua', 'space', 'white', 'plain', 'purple', 'none', 0],
    ['Cosmos Hub', 'space', 'colored', 'plain', 'green', 'none', 0],
    ['Secret Network', 'space', 'white', 'plain', 'orange', 'none', 0],
    ['Chihuahua', 'space', 'white', 'plain', 'blue', 'boots', 1],
    ['Akash Network', 'space', 'colored', 'plain', 'blue', 'stripes', 1],
    ['Akash Network', 'planet surface', 'white', 'plain', 'green', 'boots, stripes', 2],
    ['crypto.com', 'deep field', 'white', 'plain', 'purple', 'gloves, stripes', 2],
    ['Cosmos Hub', 'space', 'white', 'plain', 'blue', 'boots', 1],
    ['Terra Luna', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Chihuahua', 'space', 'colored', 'diagonal gradient', 'green', 'none', 0],
    ['BitCanna', 'space', 'colored', 'plain', 'pink', 'none', 0],
    ['Sentinel', 'space', 'white', 'plain', 'blue', 'stripes', 1],
    ['Secret Network', 'spaceship', 'white', 'plain', 'pink', 'none', 0],
    ['Secret Network', 'space', 'white', 'plain', 'cyan', 'none', 0],
    ['Sentinel', 'space', 'white', 'plain', 'pink', 'stripes', 1],
    ['Terra Luna', 'space', 'gray', 'plain', 'red', 'none', 0],
    ['Secret Network', 'space', 'white', 'plain', 'purple', 'stripes', 1],
    ['SmartNodes', 'planet surface', 'white', 'plain', 'cyan', 'gloves', 1],
    ['Cosmos Hub', 'space', 'white', 'plain', 'pink', 'none', 0],
    ['Terra Luna', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Chihuahua', 'space', 'white', 'plain', 'green', 'stripes', 1],
    ['Stargaze', 'moon surface', 'colored', 'plain', 'orange', 'boots', 1],
    ['Persistence', 'space', 'white', 'plain', 'green', 'stripes', 1],
    ['Akash Network', 'space', 'gradient', 'horizontal gradient', 'purple', 'gloves, boots, stripes', 3],
    ['BitCanna', 'planet surface', 'colored', 'plain', 'red', 'none', 0],
    ['BitSong', 'space with moon', 'white', 'plain', 'purple', 'stripes', 1],
    ['Juno', 'space', 'white', 'plain', 'red', 'stripes', 1],
    ['Sentinel', 'space', 'white', 'plain', 'yellow', 'none', 0],
    ['Chihuahua', 'space with planet', 'colored', 'plain', 'blue', 'stripes', 1],
    ['Sentinel', 'planet surface', 'colored', 'plain', 'blue', 'stripes', 1],
    ['Citadel.one', 'space', 'colored', 'plain', 'yellow', 'none', 0],
    ['Osmosis', 'space', 'white', 'horizontal gradient', 'blue', 'none', 0],
    ['Akash Network', 'space', 'white', 'plain', 'orange', 'gloves', 1],
    ['Akash Network', 'space', 'white', 'plain', 'red', 'none', 0],
    ['crypto.com', 'space', 'white', 'plain', 'pink', 'boots, stripes', 2],
    ['Sentinel', 'space', 'white', 'plain', 'blue', 'stripes', 1],
    ['Osmosis', 'space', 'colored', 'plain', 'orange', 'airdrop basket', 1],
    ['Sentinel', 'space', 'gradient', 'plain', 'pink', 'gloves, stripes', 2],
    ['Osmosis', 'space center', 'white', 'plain', 'green', 'gloves', 1],
    ['Stargaze', 'space', 'white', 'plain', 'orange', 'airdrop basket', 1],
    ['BitSong', 'space', 'white', 'plain', 'green', 'gloves', 1],
    ['Cosmos Hub', 'planet surface', 'colored', 'plain', 'red', 'none', 0],
    ['crypto.com', 'space', 'gradient', 'plain', 'green', 'gloves', 1],
    ['Juno', 'space with planet', 'white', 'plain', 'orange', 'none', 0],
    ['Terra Luna', 'space', 'white', 'plain', 'green', 'none', 0],
    ['Terra Luna', 'space', 'gray', 'plain', 'purple', 'none', 0],
    ['Stargaze', 'planet surface', 'white', 'horizontal gradient', 'pink', 'stripes', 1],
    ['Secret Network', 'space', 'white', 'plain', 'cyan', 'stripes', 1],
    ['BitCanna', 'space', 'gradient', 'plain', 'green', 'stripes, smoke', 2],
    ['Chihuahua', 'space', 'white', 'plain', 'green', 'none', 0],
    ['crypto.com', 'space', 'white', 'diagonal gradient', 'blue', 'stripes', 1],
    ['crypto.com', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Osmosis', 'space', 'gray', 'diagonal gradient', 'pink', 'stripes', 1],
    ['Akash Network', 'space', 'colored', 'diagonal gradient', 'cyan', 'none', 0],
    ['crypto.com', 'space center', 'white', 'plain', 'purple', 'stripes', 1],
    ['Terra Luna', 'moon surface', 'colored', 'plain', 'pink', 'gloves', 1],
    ['Akash Network', 'space', 'white', 'horizontal gradient', 'cyan', 'gloves, stripes', 2],
    ['Cosmos Hub', 'space', 'white', 'diagonal gradient', 'green', 'none', 0],
    ['Cosmos Hub', 'space', 'white', 'plain', 'cyan', 'boots, stripes', 2],
    ['Regen Network', 'space', 'white', 'plain', 'green', 'none', 0],
    ['Chihuahua', 'spaceship', 'rainbow', 'plain', 'blue', 'stripes', 1],
    ['Stargaze', 'space', 'white', 'plain', 'blue', 'stripes, airdrop basket', 2],
    ['Chihuahua', 'space', 'white', 'plain', 'red', 'none', 0],
    ['Osmosis', 'space', 'gray', 'plain', 'blue', 'none', 0],
    ['Chihuahua', 'space with moon', 'white', 'plain', 'blue', 'none', 0],
    ['crypto.com', 'space', 'white', 'plain', 'yellow', 'stripes', 1],
    ['Juno', 'space', 'white', 'plain', 'red', 'none', 0],
    ['Akash Network', 'space', 'gray', 'plain', 'blue', 'gloves', 1],
    ['Sentinel', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Stargaze', 'space', 'white', 'plain', 'pink', 'none', 0],
    ['Juno', 'planet surface', 'colored', 'plain', 'red', 'none', 0],
    ['Cosmos Hub', 'space with planet', 'white', 'plain', 'red', 'boots', 1],
    ['Cosmos Hub', 'space', 'white', 'plain', 'yellow', 'none', 0],
    ['Chihuahua', 'space', 'colored', 'plain', 'cyan', 'none', 0],
    ['BitSong', 'space', 'white', 'plain', 'purple', 'none', 0],
    ['Secret Network', 'space', 'colored', 'plain', 'yellow', 'none', 0],
    ['Comdex', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Persistence', 'space', 'white', 'plain', 'blue', 'boots', 1],
    ['Stargaze', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Stargaze', 'space', 'white', 'plain', 'green', 'stripes, airdrop basket', 2],
    ['Akash Network', 'moon surface', 'white', 'plain', 'blue', 'boots', 1],
    ['Secret Network', 'galaxy', 'gradient', 'plain', 'green', 'none', 0],
    ['Terra Luna', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Chihuahua', 'space', 'white', 'plain', 'pink', 'none', 0],
    ['Sentinel', 'space with planet', 'white', 'diagonal gradient', 'green', 'stripes', 1],
    ['Regen Network', 'space', 'white', 'plain', 'orange', 'stripes', 1],
    ['Neta', 'space', 'colored', 'horizontal gradient', 'blue', 'none', 0],
    ['Sentinel', 'space', 'colored', 'plain', 'cyan', 'none', 0],
    ['Cosmos Hub', 'galaxy', 'colored', 'plain', 'red', 'none', 0],
    ['crypto.com', 'space', 'white', 'plain', 'orange', 'none', 0],
    ['Terra Luna', 'space', 'colored', 'plain', 'purple', 'boots', 1],
    ['Secret Network', 'space', 'white', 'diagonal gradient', 'purple', 'none', 0],
    ['Stargaze', 'space', 'gray', 'plain', 'red', 'comet', 1],
    ['Persistence', 'galaxy', 'gradient', 'plain', 'green', 'stripes', 1],
    ['Osmosis', 'space', 'white', 'diagonal gradient', 'blue', 'none', 0],
    ['Terra Luna', 'planet surface', 'white', 'plain', 'blue', 'boots', 1],
    ['Sentinel', 'spaceship', 'white', 'horizontal gradient', 'orange', 'stripes', 1],
    ['Akash Network', 'space', 'colored', 'plain', 'blue', 'comet', 1],
    ['Racoon', 'space', 'white', 'plain', 'pink', 'none', 0],
    ['Osmosis', 'space', 'white', 'plain', 'purple', 'boots', 1],
    ['BitCanna', 'space', 'white', 'plain', 'green', 'smoke', 1],
    ['Akash Network', 'space', 'white', 'plain', 'green', 'stripes', 1],
    ['Juno', 'space', 'white', 'plain', 'blue', 'stripes', 1],
    ['Cosmos Hub', 'space', 'white', 'horizontal gradient', 'blue', 'none', 0],
    ['Racoon', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['Terra Luna', 'space', 'white', 'plain', 'purple', 'none', 0],
    ['Persistence', 'space', 'white', 'diagonal gradient', 'blue', 'stripes', 1],
    ['Stargaze', 'space', 'white', 'plain', 'pink', 'boots', 1],
    ['Sentinel', 'planet surface', 'white', 'plain', 'purple', 'stripes', 1],
    ['Terra Luna', 'moon surface', 'white', 'plain', 'blue', 'none', 0],
    ['Secret Network', 'space', 'gray', 'plain', 'blue', 'none', 0],
    ['Chihuahua', 'space', 'white', 'plain', 'blue', 'stripes', 1],
    ['Secret Network', 'space', 'gray', 'plain', 'green', 'stripes', 1],
    ['Akash Network', 'space', 'colored', 'horizontal gradient', 'green', 'stripes', 1],
    ['Akash Network', 'space', 'colored', 'plain', 'orange', 'none', 0],
    ['Juno', 'space with planet', 'white', 'plain', 'green', 'stripes', 1],
    ['Sentinel', 'space', 'white', 'plain', 'blue', 'none', 0],
    ['crypto.com', 'space', 'colored', 'plain', 'pink', 'none', 0],
    ['Sentinel', 'space', 'white', 'plain', 'blue', 'none', 0],
];
